# -*- coding: utf-8 -*-
"""eda-ydata_profiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11aOnwsJWAnRSYuaWdOsWwhnAeg7ob2Zu
"""

import pandas as pd
from ydata_profiling import ProfileReport

# Specify the path to your dataset
path = '/content/gurgaon_properties_post_feature_selection_v2.csv'

# Load your dataset and drop duplicates
df = pd.read_csv(path).drop_duplicates()

# Create the ProfileReport object
profile = ProfileReport(df, title='YData Profiling Report', explorative=True)

# Generate the report and save it to an HTML file
profile.to_file("EDA_report.html")

